/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Customer = t.iface([], {
  id: "string",
  name: "string",
});

const exportedTypeSuite: t.ITypeSuite = {
  Customer,
};
export default exportedTypeSuite;
