/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Gender = t.union(t.lit("male"), t.lit("female"), t.lit("other"));

export const Employee = t.iface([], {
  id: "number",
  first_name: "string",
  last_name: "string",
  title: t.opt("string"),
  phone: "string",
  email: "string",
  gender: "Gender",
  birth_date: "Date",
  date_of_employment: t.opt("Date"),
  termination_date: t.opt("Date"),
  emergency_contact_name: t.opt("string"),
  emergency_contact_phone: t.opt("string"),
  emergency_contact_relation: t.opt("string"),
  address: t.opt("string"),
  postal_code: t.opt("string"),
  city: t.opt("string"),
  image_url: t.opt("string"),
  has_permanent_position: t.opt("boolean"),
  emoji: t.opt("string"),
  role: t.opt("string"),
  bio: t.opt("string"),
});

export const Employees = t.array("Employee");

const exportedTypeSuite: t.ITypeSuite = {
  Gender,
  Employee,
  Employees,
};
export default exportedTypeSuite;
