/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Billable = t.union(
  t.lit("billable"),
  t.lit("nonbillable"),
  t.lit("unavailable")
);

export const Project = t.iface([], {
  id: "string",
  name: "string",
  billable: "Billable",
  customer: "string",
  responsible: t.opt("number"),
  active: "boolean",
  deductable: t.opt("boolean"),
});

export const Projects = t.array("Project");

const exportedTypeSuite: t.ITypeSuite = {
  Billable,
  Project,
  Projects,
};
export default exportedTypeSuite;
