/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Project = t.iface([], {
  id: "string",
  name: "string",
  billable: "boolean",
  customer: "string",
  responible: t.opt("number"),
  active: "boolean",
  deductable: t.opt("boolean"),
});

const exportedTypeSuite: t.ITypeSuite = {
  Project,
};
export default exportedTypeSuite;
