/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes
/* eslint-disable @typescript-eslint/camelcase */

export const TokenData = t.iface([], {
  id_token: "string",
  apiToken: "string",
  config: t.iface([], {
    apiUri: "string",
  }),
  userEmail: "string",
});

const exportedTypeSuite: t.ITypeSuite = {
  TokenData,
};
export default exportedTypeSuite;
